# Frontend Dockerfile (dev)
FROM node:18-alpine

WORKDIR /app

# Cài dependency
COPY package*.json ./
RUN npm ci

# Copy source
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
