version: "3.9"

services:
  api:
    build: .
    container_name: HotelBookingSystem_API
    env_file:
      - .env
    ports:
      - "8000:8000"  # Map localhost:8000 -> container:8000
    depends_on:
      - db
      - redis
    command: >
      uv run uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  worker:
    build: .
    container_name: HotelBookingSystem_worker
    env_file:
      - .env
    depends_on:
      - redis
      - db
    command: >
      uv run celery -A app.worker.celery_app worker --loglevel=INFO

  

  db:
    image: postgres:15-alpine
    container_name: HotelBookingSystem_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nguyndz123
      POSTGRES_DB: HotelBookingSystem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: HotelBookingSystem_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
